# Netlify Build Configuration for Hugo Blox + Pagefind
[build]
  command = """
    set -e
    echo "=== Starting Hugo Blox build ==="
    echo "Node version: $(node --version)"
    echo "pnpm version: $(pnpm --version)"
    echo "Hugo version: $(hugo version)"
    echo "Go version: $(go version || echo 'Go not available')"
    
    echo "=== Installing dependencies ==="
    pnpm install --verbose
    
    echo "=== Running Hugo build ==="
    hugo --gc --minify -b $URL --logLevel debug --printI18nWarnings --printPathWarnings
    
    echo "=== Running Pagefind indexing ==="
    pnpm dlx pagefind --source 'public' --verbose
    
    echo "=== Build completed successfully ==="
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.149.0"       # 你本地 Hugo 版本
  GO_VERSION = "1.25.0"           # 你本地 Go 版本
  NODE_VERSION = "22"             # Netlify Node 版本
  HUGO_ENABLEGITINFO = "true"    # 显示文章更新时间
  HUGO_LOG_I18N_WARNINGS = "true"
  HUGO_LOG_WARNINGS = "true"
  FORCE_COLOR = "1"
  PNPM_LOG_LEVEL = "debug"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = """
    set -e
    echo "=== Deploy Preview Build ==="
    echo "Deploy URL: $DEPLOY_PRIME_URL"
    pnpm install --verbose
    hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --logLevel debug --printI18nWarnings --printPathWarnings
    pnpm dlx pagefind --source 'public' --verbose
  """

[context.branch-deploy]
  command = """
    set -e
    echo "=== Branch Deploy Build ==="
    echo "Deploy URL: $DEPLOY_PRIME_URL"
    pnpm install --verbose
    hugo --gc --minify -b $DEPLOY_PRIME_URL --logLevel debug --printI18nWarnings --printPathWarnings
    pnpm dlx pagefind --source 'public' --verbose
  """

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

